catalog:
  services:
    - id: java-service-broker-id
      name: java-service-broker
      description: A simple java-service-broker
      bindable: true
      plans:
        - id: example-plan-id
          name: standard
          description: A simple plan